from __future__ import annotations

from typing import Any, Protocol


class ProgressBackend(Protocol):
    """Internal progress backend contract used by mqdm runtime and bars."""

    multiprocess: bool

    # ---------------------------------- Control --------------------------------- #

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def refresh(self) -> None: ...

    # ---------------------------------- Output ---------------------------------- #

    def write(self, *args: Any, **kw: Any) -> Any: ...

    # ------------------------------ Task Management ----------------------------- #

    def add_task(self, **task_kw: Any) -> int: ...
    def load_task(self, task: dict[str, Any], start: bool = True) -> None: ...
    def try_update(self, task_id: int, **task_update: Any) -> None: ...
    def dump_task(self, task_id: int) -> dict[str, Any] | None: ...
    def pop_task(self, task_id: int, remove: bool | None = None) -> dict[str, Any] | None: ...
    def clear(self) -> None: ...

    # ----------------------------------- Proxy ---------------------------------- #

    def convert_proxy(self, runtime=None) -> ProgressBackend: ...
